name: Build and Push Docker Image on Release

on:
  release:
    types:
      - created

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract release tag
        id: release_tag
        run: echo "tag=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT

      - name: Build Docker image with release tag and latest
        run: |
          docker build \
            -t ghcr.io/${{ github.repository }}:${{ steps.release_tag.outputs.tag }} \
            -t ghcr.io/${{ github.repository }}:latest \
            .

      - name: Push Docker images
        run: |
          REPO=$(echo "ghcr.io/${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          TAG=${{ steps.release_tag.outputs.tag }}
          docker push $REPO:$TAG
          docker push $REPO:latest
